### PR TITLE
Complete 1 task from TODO list

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Area owners can now accept area requests from other users.
- Various message improvements.
- Translation updates.

The features above are only compatible with [`areas`](https://github.com/minetest-mods/areas).

## To do

- [x] If there are multiple area owners, the request won't be sent to any of the owners, nor any can't accept requests.
- [x] When a request is sent it doesn't checks if the area owner is online.
- [ ] If there are multiple areas, various messages will be doubled.
- [x] If an owner accepts an area request, the other requests sent to other owners will crash the server as soon as they get accepted, because `target_coords` is set to **`nil`**.

## How to test

- 1. Open 3 Minetest Engines; connect all accounts to a local server.

Let's say the first player is named `test1`.
The second is `test2`; the third is `test3`.

- 2. Now, send an area request from `test3` to `test2`; now `test2` will send a request to `test1`.

Now, accept request from `test3` to `test2`.
Accept request from `test2` `test1`.

Please test and inform me of any other issues/crashes.
If you have a bugfix, post it here or create a PR.

### CODE REVIEW

**Comment by ChaosWormz** [comment]
2020-01-29 20:20:18: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'tpr' in callback on_chat_message(): ...username/apps/minetest/bin/../builtin/common/misc_helpers.lua:487: attempt to index local 'pos' (a nil value)
2020-01-29 20:20:18: ERROR[Main]: stack traceback:
2020-01-29 20:20:18: ERROR[Main]: 	...username/apps/minetest/bin/../builtin/common/misc_helpers.lua:487: in function 'pos_to_string'
2020-01-29 20:20:18: ERROR[Main]: 	...e/username/apps/minetest/bin/../mods/tpr/functions.lua:474: in function 'func'
2020-01-29 20:20:18: ERROR[Main]: 	/home/username/apps/minetest/bin/../builtin/game/chat.lua:69: in function </home/username/apps/minetest/bin/../builtin/game/chat.lua:48>
2020-01-29 20:20:18: ERROR[Main]: 	...username/apps/minetest/bin/../builtin/game/register.lua:429: in function <...username/apps/minetest/bin/../builtin/game/register.lua:413>
2020-01-29 20:20:18: ERROR[Main]: Access denied. Reason: This server has experienced an internal error. You will now be disconnected.

**Comment by Panquesito7** [comment]
@ChaosWormz thanks for spotting the bug! Fixed. 🙂

**Comment by Panquesito7** [comment]
Everything is working as excepted; tested with MT 5.1.0.
However, I've tried several ways of storing `target_coords` per player, but none of them work.

I have a temporary fix, but if this is going to be implemented, this needs to fixed before it can get merged.

**Comment by Panquesito7** [comment]
I've finally fixed `tpc_target_coords` being re-writed each time an area request is sent.
Sorry for the long delay!

Tested; works perfect.
@ChaosWormz, please re-review and re-test these changes.

**Comment by ChaosWormz** [comment]
2020-03-04 11:12:20: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'tpr' in callback on_chat_message(): ...rmz/games/minetest/bin/../builtin/common/misc_helpers.lua:482: attempt to index local 'pos' (a nil value)
2020-03-04 11:12:20: ERROR[Main]: stack traceback:
2020-03-04 11:12:20: ERROR[Main]: 	...ame/games/minetest/bin/../builtin/common/misc_helpers.lua:482: in function 'pos_to_string'
2020-03-04 11:12:20: ERROR[Main]: 	...e/username/games/minetest/bin/../mods/tpr/functions.lua:488: in function 'func'
2020-03-04 11:12:20: ERROR[Main]: 	/home/username/games/minetest/bin/../builtin/game/chat.lua:69: in function </home/username/games/minetest/bin/../builtin/game/chat.lua:48>
2020-03-04 11:12:20: ERROR[Main]: 	...username/games/minetest/bin/../builtin/game/register.lua:429: in function <...username/games/minetest/bin/../builtin/game/register.lua:413>

**Comment by Panquesito7** [comment]
@ChaosWormz ping.

**Pull request merged**
