### PR TITLE
Move to MT 5.0.0+ translation system

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Update translation system to MT 5.0.0 and above.
  - Benefits include client-side translations.
- Remove `intllib` support.

## To do
Ready for review.

## How to test
Check all commands, descriptions and strings in Spanish or Brazilian Portuguese.

### CODE REVIEW

**Comment by Panquesito7** [comment]
@ChaosWormz ping.

**Comment by ChaosWormz** [comment]
languages don't seem to work for me

**Comment by Panquesito7** [comment]
That's weird, Spanish language is working fine for me.
Do you have any other issues?

**Comment by ChaosWormz** [comment]
changing languages doesn't work for me at all, the entire minetest is unaffected by the language setting. so i cannot help with testing this. something's definitely wrong with with my installation.

**Comment by Panquesito7** [comment]
Hmm, it's working fine for me.
Are you sure you've changed the language correctly?

Did you change it via Minetest Settings tab, or by editing `minetest.conf`?
I have my language set as spanish via `minetest.conf`:
```
language = es
```

**Comment by Panquesito7** [comment]
@ChaosWormz what version of Minetest are you using?

**Comment by ChaosWormz** [comment]
Using the latest git

**Comment by Panquesito7** [comment]
It is too weird that it is not working.
It works perfectly for me. Are you sure the language is set to Spanish?

**Comment by Panquesito7** [comment]
I will re-create this PR and merge it. It works fine for me.

**Pull request closed without merging**
